[package]
name = "solidjs-remixicon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
convert_case = "0.6.0"
glob = "0.3.1"
