on:
  # schedule:
  #   - cron: '32 4 * * *'
  push

jobs:
  build:
    name: Check to publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20.8.1
      
      - name: Check to build and publish
        run: bash ./check_to_publish.bash
