on:
  # schedule:
  #   - cron: '32 4 * * *'
  workflow_dispatch

jobs:
  build:
    name: Check to publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v3
      
      - name: Check to build and publish
        run: bash ./check_to_publish.bash
